from pydantic import BaseModel, Field
from typing import Dict, Optional

class Info(BaseModel):
    taskId: str = Field(None, description="任务ID")
    taskType: str = Field(None, description="任务类型")
    taskName: str = Field(None, description="任务名称")
    brokerIp: str = Field(None, description="代理IP")
    serverTag: str = Field(None, description="服务器标签")
    cycleUnit: str = Field(None, description="周期单位")
    cycleNum: str = Field(None, description="周期数")
    startDate: str = Field(None, description="开始日期")
    endDate: str = Field(None, description="结束日期")
    selfDepend: str = Field(None, description="自依赖")
    taskAction: str = Field(None, description="任务动作")
    tryLimit: str = Field(None, description="尝试限制")
    delayTime: str = Field(None, description="延迟时间")
    startupTime: str = Field(None, description="启动时间")
    aliveWait: str = Field(None, description="存活等待时间")
    retriable: str = Field(None, description="是否可重试")
    status: str = Field(None, description="状态")
    taskPriority: str = Field(None, description="任务优先级")
    taskGroup: str = Field(None, description="任务组")
    notes: str = Field(None, description="备注")
    inCharge: str = Field(None, description="负责人")
    createTime: str = Field(None, description="创建时间")
    lastUpdate: str = Field(None, description="最后更新时间")
    oldId: str = Field(None, description="旧ID")
    sourceServer: str = Field(None, description="源服务器")
    targetServer: str = Field(None, description="目标服务器")
    topicName: str = Field(None, description="主题名称")
    moduleName: str = Field(None, description="模块名称")
    runOverTime: str = Field(None, description="运行超时时间")
    unSuccessOverTime: str = Field(None, description="不成功超时时间")
    scheduleType: str = Field(None, description="调度类型")
    dataType: str = Field(None, description="数据类型")
    taskDesc: str = Field(None, description="任务描述")
    updateBy: str = Field(None, description="更新者")
    upddateDate: str = Field(None, description="更新日期")
    unRunOverTime: str = Field(None, description="未运行超时时间")
    advanceInit: str = Field(None, description="提前初始化")
    developer: str = Field(None, description="开发者")
    sourceTables: str = Field(None, description="源表")
    aitTables: str = Field(None, description="AIT表")
    exeEnvironment: str = Field(None, description="执行环境")
    exec_script_type: str = Field(None, description="执行脚本类型")
    task_relation: str = Field(None, description="任务关系")
    monitorPlatform_access: str = Field(None, description="监控平台访问")
    approval: str = Field(None, description="审批")
    approval_status: str = Field(None, description="审批状态")
    version_timestamp: str = Field(None, description="版本时间戳")
    timeout_early_warning: str = Field(None, description="超时预警")
    data_date_type: str = Field(None, description="数据日期类型")
    applicant: str = Field(None, description="申请人")
    applicant_time: str = Field(None, description="申请时间")
    approval_comment: str = Field(None, description="审批意见")
    skip_festival: str = Field(None, description="跳过节日")
    exec_script_path: str = Field(None, description="执行脚本路径")
    exec_script_parms: str = Field(None, description="执行脚本参数")
    exec_user_name: str = Field(None, description="执行用户名")
    skip_weeken: str = Field(None, description="跳过周末")
    unsuccessful_early_warning: str = Field(None, description="不成功预警")
    approval_result: str = Field(None, description="审批结果")
    ignore_empty_datasource: str = Field(None, description="忽略空数据源")
    hive_database: str = Field(None, description="Hive数据库")
    relational_table: str = Field(None, description="关系表")
    horaeAlert_check_lines: str = Field(None, description="HoraeAlert检查行数")
    collection_tool_type: str = Field(None, description="采集工具类型")
    file_storage_format: str = Field(None, description="文件存储格式")
    hive_type_check: str = Field(None, description="Hive类型检查")
    ignore_empty_datasource1: str = Field(None, description="忽略空数据源1")
    relational_database: str = Field(None, description="关系数据库")
    hive_table_name: str = Field(None, description="Hive表名")
    select_sql: str = Field(None, description="选择SQL")
    field_map_json: str = Field(None, description="字段映射JSON")
    hive_partition_value: str = Field(None, description="Hive分区值")
    field_json: str = Field(None, description="字段JSON")
    db_database_name: str = Field(None, description="数据库名称")
    source_table_name: str = Field(None, description="源表名称")
    truncate_sql: str = Field(None, description="截断SQL")
    load_mode: str = Field(None, description="加载模式")
    source_database_name: str = Field(None, description="源数据库名称")  
    insert_sql: str = Field(None, description="插入SQL")  



if __name__ == "__main__":

    data = {
        "taskId": "12",
        "taskName": "12",
        "inCharge": "12",
        "startDate": "345",
        # "select.sql":"123",
        "unSuccessOverTime": "12"
    }
    info = Info(**data)
    print(info)
