FROM python:3.10.13

RUN pip3 install pycryptodome crypto requests_toolbelt uvicorn requests fastapi psycopg2-binary sseclient-py httpx python-multipart sqlalchemy mysqlclient aiomysql pymysql python-dotenv-i https://mirrors.aliyun.com/pypi/simple/
